### ISSUE TITLE
csrf校验失败

### ISSUE THREAD

**Issue by jzl2163** [idiotbaka/bilibiliAutoCoinExp#1]
在自己电脑与服务器均试验过，获取今日经验与番剧列表均正常，但投币时显示csrf校验失败。

**Comment by dongfg** [comment]
https://github.com/idiotbaka/bilibiliAutoCoinExp/blob/79114768c92785f0d276f386c835f953ab30aacd/run.php#L78
这行下面加一个提交字段 `'cross_domain' => true,`， 添加后的提交字段：
```
    $send_coin_result = php_curl('https://api.bilibili.com/x/web-interface/coin/add', $header, 1, [
        'aid' => $v,
        'multiply' => 1,
	'cross_domain' => true,
        'csrf' => $crsf
    ]);
```
