### ISSUE TITLE
csrf 校验失败的可能原因

### ISSUE THREAD

**Issue by oldzhg** [idiotbaka/bilibiliAutoCoinExp#2]
直接运行会报错，csrf 校验失败。
后来抓包发现请求中数据填写错误，被分成了很多块
```
Content-Disposition: form-data; name="aid"
883080021
Content-Disposition: form-data; name="multiply"
1
Content-Disposition: form-data; name="csrf"
xxxx
```

将164行的`$postdata`修改成`http_build_query($postdata)`，post数据正确
```
aid=883080021&multiply=1&csrf=xxxx
```

**Comment by idiotbaka** [comment]
非常感谢！已修复。
这个可能是因为不同系统的curl处理问题造成的。没指定header的Content-type时，提交给CURLOPT_POSTFIELDS数组时，好像有的系统指定为application/x-www-form-urlencoded，有的指定为application/json
